apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo-app
  namespace: test
  labels:
    app: http-echo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo-app
  template:
    metadata:
      labels:
        app: http-echo-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: http-echo-app
        image: hashicorp/http-echo
        imagePullPolicy: Always
        ports:
        - containerPort: 5678