apiVersion: v1
kind: Service
metadata:
  name: cxas-service
  namespace: poc-caixa
spec:
  selector:
    app: cxas-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP