apiVersion: v1
kind: Service
metadata:
  name: http-echo-app
  namespace: test
spec:
  selector:
    app: http-echo-app
  ports:
    - protocol: TCP
      port: 80
      targetPorPt: 5678
  type: ClusterI